<a href="https://colab.research.google.com/github/DattaIn/idatta.github.io/blob/master/CDS_B1_M0_NB_Inclass_04_LinearAlgebra_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Notebook Inclass 4: Linear Algebra & Calculus


## Learning Objectives

At the end of the experiment, you will be able to :

* perform scalar and matrix addition, subtraction, multiplication, and division operations
* implement derivative functions using SymPy library



### Importing required packages

In [1]:
import numpy as np
from matplotlib import pyplot as plt

### Creating arrays, scalars, and matrices in Python

In [2]:
# creating a scalar
x = .5
print(x)

0.5


In [3]:
# Creating a vector
vec = [1, 2, 3]
x_vector = np.array(vec)
print(x_vector)

y_vector = np.array([6, 7, 8])
print(y_vector)

[1 2 3]
[6 7 8]


In [4]:
# Creating a matrix
matrix1 = np.array(list(zip(x_vector,y_vector)))
print("matrix 1",matrix1)

matrix2 = np.array([[12, 13, 14],[11, 15, 16]])
print("\n maxtrix 2",matrix2)

matrix 1 [[1 6]
 [2 7]
 [3 8]]

 maxtrix 2 [[12 13 14]
 [11 15 16]]


### Matrix operations

#### Matrix Addition and Subtraction

In [5]:
print(matrix1)
print(3 + matrix1)

[[1 6]
 [2 7]
 [3 8]]
[[ 4  9]
 [ 5 10]
 [ 6 11]]


In [6]:
# matrix2 is transposed to match the shape
add_matrix = matrix1 + matrix2.T
print(add_matrix)

sub_matrix = matrix1 - matrix2.T
print("\n",sub_matrix)

[[13 17]
 [15 22]
 [17 24]]

 [[-11  -5]
 [-11  -8]
 [-11  -8]]


#### Multiplication and Inverse of a matrix

In [7]:
# matrix multiplication
matrix1 @ matrix2

array([[ 78, 103, 110],
       [101, 131, 140],
       [124, 159, 170]])

**Inverse of a matrix**:  

if a matrix A = $\begin{bmatrix} a & b\\ c & d \end{bmatrix}$ then $A^{-1}$ =  $\begin{bmatrix} a & b\\ c & d \end{bmatrix}^{-1}$ = $\frac{1}{det A}$ $\begin{bmatrix} d & -b\\ c & a \end{bmatrix}$ = $\frac{1}{ad-bc}$ $\begin{bmatrix} d & -b\\ c & a \end{bmatrix}$

If $det A$ is equal to zero, the inverse of A does not exist.

In [8]:
A = np.array([[1,2],[3,4]])
print(A)
A_inverse = np.linalg.inv(A)
print("\n",A_inverse)

[[1 2]
 [3 4]]

 [[-2.   1. ]
 [ 1.5 -0.5]]


Let's compute $2I - 4B + AB$ for $A$ = $\begin{bmatrix} 1 & 2\\ 3 & 7 \end{bmatrix}$,  $B$ = $\begin{bmatrix} 6 & 4 \\ 1 & 2 \end{bmatrix}$ $I$ is the identity matrix of size 2

In [9]:
A = np.array([[1, 2], [3, 7]])
B = np.array([[6, 4], [1, 2]])

# Identity matrix
I = np.eye(2)

2 * I - 4 * B + A@B

array([[-14.,  -8.],
       [ 21.,  20.]])

#### Solve a set of linear equations

$ 4X + 3Y + 2Z = 25 $

$ -2X + 2Y + 3Z = -10 $

$ 3X - 5Y + 2Z = -4 $

In [ ]:
A1 = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B1 = np.array([25, -10, -4])
X2 = np.linalg.solve(A1,B1)

print(X2)

In [11]:
# Check that the solution is correct
np.allclose(np.dot(A1, X2), B1)

True

#### Matrix Power

Matrix power of 2 is multiplication of a matrix 2 times it self; For eg, $A^2$  = $A*A$

`numpy.linalg` has a function `matrix_power`

In [12]:
from numpy.linalg import matrix_power as mpow

print(A)
print("Matrix power of 2 is\n",mpow(A,2))
print(A@A)

[[1 2]
 [3 7]]
Matrix power of 2 is
 [[ 7 16]
 [24 55]]
[[ 7 16]
 [24 55]]


#### Determinant and Trace of a matrix

Trace is the sum of diagonal elements of a matrix

We find the determinant using the function `scipy.linalg.det`

In [13]:
import scipy.linalg as la
print("Trace of a matrix A is ",np.trace(A))
print("Determinant of a matrix", la.det(A))

Trace of a matrix A is  8
Determinant of a matrix 1.0


### Eigen values and Eigen vectors

Let A be a square matrix. A non-zero vector v is an eigenvector for A with eigenvalue $\lambda$ if Av = $\lambda$v

Rearranging the equation, (A- $\lambda I$)v = 0, where I is the identity matrix

In [14]:
eigvals, eigvecs = la.eig(A)
print(eigvals)
print(eigvecs)

[0.12701665+0.j 7.87298335+0.j]
[[-0.91649636 -0.2794051 ]
 [ 0.40004303 -0.96017331]]


### The Derivative of a Single Variable Functions

The derivative of a function is the rate of change of the function which can be calculated using the ratio of change of the function Δy to the change of the independent variable Δx.

$f(x) = x^n \rightarrow f{}'(x) = nx^{n-1}$

In [15]:
import sympy as sp
x = sp.Symbol('x')

# Power rule
func = x**5
sp.diff(func)

5*x**4

In [16]:
# Product rule
func1 = (x**2 + 1) * sp.cos(x)
sp.diff(func1)

2*x*cos(x) - (x**2 + 1)*sin(x)

In [17]:
# Chain rule
sp.diff( (x**2 - 2 *x + 6)** 3)

(6*x - 6)*(x**2 - 2*x + 6)**2

### The Derivative of multi variable functions

In [18]:
x, y, z = sp.symbols('x y z')

f = x**3 + 2 * x**2 * y + 2 * x * z
deriv_f = sp.diff(f,x)

Above are equations and their derivatives without numerical values,  To add numerical implementation to function use `sympy.lambdify`.

In [19]:
f1 =  sp.lambdify(x, deriv_f)
f1(2)

8*y + 2*z + 12

### Limit Function

SymPy can compute symbolic limits with the limit function.

The syntax to compute $ \lim_{x \to x_0} f(x) $ is `sympy.limit(f(x), x, x0)`

In [20]:
x = sp.Symbol('x')

sp.limit(sp.sin(x) / x , x, 0)

1